[database]
address = "127.0.0.1"
port = "3306"
user = "root"
password = "password"
database = "maplestory"

[channel]
worldAddress = "127.0.0.1"
worldPort = "8584"
listenAddress = "0.0.0.0"
listenPort = "8684"
ClientConnectionAddress = "192.168.1.240"
packetQueueSize = 512
MaxPop = 250
