[database]
address = "127.0.0.1"
port = "3306"
user = "root"
password = "password"
database = "maplestory"

[login]
clientListenAddress = "0.0.0.0"
clientListenPort = "8484"
serverListenAddress = "0.0.0.0"
serverListenPort = "8485"
packetQueueSize = 512
# The following should be set to zero when not testing on a local network environment
latency = 250
jitter = 250